project_id = "twaqppiracythbmwyjnn"

[functions.create-user]
verify_jwt = true

[functions.procesar-pago]
verify_jwt = false

[functions.get-auth-logs]
verify_jwt = true

[functions.send-invoice]
verify_jwt = false